repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: double-quote-string-fixer
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "dev"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.56.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependancies:
          - eslint@8.56.0
          - eslint-config-next@14.2.1

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v3.2.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|css|json)$
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-tailwindcss@0.5.13
